rule download_ngs_te_mapper2:
    output:
        config['ngs_te_mapper2']['target']
    params:
        url = config['ngs_te_mapper2']['url'],
        commit = config['ngs_te_mapper2']['commit'],
        log = config['ngs_te_mapper2']['log'],
        install_path = config['ngs_te_mapper2']['install_path']
    conda: config['ngs_te_mapper2']['env_download']
    script: config['ngs_te_mapper2']['script']

rule download_vep:
    output:
        config['vep']['target']
    params:
        log = config['vep']['log'],
        cache_dir = config['vep']['cache_dir'],
        assembly = config['vep']['only_assembly'],
        exists = False
    conda: config['vep']['env']
    script: config['vep']['script']

rule download_vep_assembly:
    output:
        config['vep']['target'] + f".{config['vep']['only_assembly']}.txt"
    params:
        log = config['vep']['log'],
        cache_dir = config['vep']['cache_dir'],
        assembly = config['vep']['only_assembly'],
        exists = True
    conda: config['vep']['env']
    script: config['vep']['script']